apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: sample-resource
  title: SampleR
  description: This is a sandbox resource to learn about catalog entries
  tags: 
    - java
    - sso
    - client
  annotations:
    github.com/project-slug: mark-dutra/sample-resource
spec:
  type: service
  lifecycle: experimental
  owner: devsecops
  system: java
